### ISSUE TITLE
Programación para el Personal

### ISSUE THREAD

**Issue by Rencas1207** [Rencas1207/SistemaDeAsistencias#11]
- [x] Tarea Pendiente 1: Insertar Personal
- [x] Tarea Pendiente 2: Editar Personal
- [x] Tarea Pendiente 3: Mostrar Personal
- [x] Tarea Pendiente 4: Eliminar Personal
- [x] Tarea Pendiente 5: Buscar Personal

**Comment by Shiarir** [comment]
Listo

**Comment by Shiarir** [comment]
listo

**Comment by Shiarir** [comment]
listo
